In [14]:
from optimum.intel.openvino import OVStableDiffusionXLPipeline
# from nncf import compress_weights, CompressWeightsMode
model_id = "stabilityai/stable-diffusion-xl-base-1.0"


ov_pipe_bf16 = OVStableDiffusionXLPipeline.from_pretrained(model_id, compile=False, export=True, load_in_8bit=False)
# ov_pipe_bf16
type(ov_pipe_bf16.text_encoder.model)


Framework not specified. Using pt to export to ONNX.
Keyword arguments {'subfolder': '', 'trust_remote_code': False} are not expected by StableDiffusionXLImg2ImgPipeline and will be ignored.


Loading pipeline components...:   0%|          | 0/7 [00:00<?, ?it/s]

Using framework PyTorch: 2.1.0+cu121
/home/devuser/nlyalyus/env/lm-eval-repro/lib/python3.8/site-packages/transformers/modeling_attn_mask_utils.py:86: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if input_shape[-1] > 1 or self.sliding_window is not None:
/home/devuser/nlyalyus/env/lm-eval-repro/lib/python3.8/site-packages/transformers/modeling_attn_mask_utils.py:161: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if past_key_values_length > 0:
/home/devuser/nlyalyus/env/lm-eval-repro/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py

openvino.runtime.ie_api.Model

In [3]:
print(ov_pipe_bf16)

OVStableDiffusionXLPipeline {
  "_class_name": "OVStableDiffusionXLPipeline",
  "_diffusers_version": "0.21.4",
  "add_watermarker": null,
  "force_zeros_for_empty_prompt": true,
  "scheduler": [
    "diffusers",
    "EulerDiscreteScheduler"
  ],
  "text_encoder": [
    "optimum",
    "OVModelTextEncoder"
  ],
  "text_encoder_2": [
    "optimum",
    "OVModelTextEncoder"
  ],
  "tokenizer": [
    "transformers",
    "CLIPTokenizer"
  ],
  "tokenizer_2": [
    "transformers",
    "CLIPTokenizer"
  ],
  "unet": [
    "optimum",
    "OVModelUnet"
  ],
  "vae_decoder": [
    "optimum",
    "OVModelVaeDecoder"
  ],
  "vae_encoder": [
    "optimum",
    "OVModelVaeEncoder"
  ]
}



In [10]:
from optimum.intel import OVQuantizer
from optimum.intel import OVConfig
quantizer = OVQuantizer.from_pretrained(ov_pipe_bf16.text_encoder.model)
quantizer.quantize(save_directory='', weights_only=True, quantization_config=OVConfig(compression={"type": "int4_sym_g128", "ratio": 0.8}),)

AttributeError: 'Model' object has no attribute 'forward'

In [13]:
type(ov_pipe_bf16.text_encoder.model)

AttributeError: 'Model' object has no attribute 'text_encoder'

In [12]:
from nncf import compress_weights, CompressWeightsMode
compressed_text_encoder = compress_weights(ov_pipe_bf16.text_encoder.model, mode=CompressWeightsMode.INT4_SYM, group_size=128, ratio=0.8)

Output()

INFO:nncf:Statistics of the bitwidth distribution:
+--------------+---------------------------+-----------------------------------+
| Num bits (N) | % all parameters (layers) |    % ratio-defining parameters    |
|              |                           |             (layers)              |
+==============+===========================+===================================+
| 8            | 47% (30 / 74)             | 21% (27 / 71)                     |
+--------------+---------------------------+-----------------------------------+
| 4            | 53% (44 / 74)             | 79% (44 / 71)                     |
+--------------+---------------------------+-----------------------------------+


Output()

In [37]:
from pathlib import Path
path = Path('/dev/data/nlyalyus/cache/opt-6.7b/int4_asym_g64')
from openvino import Core
core = Core()

In [38]:
compressed_model = core.read_model(model=str(path / 'openvino_model.xml'))

In [43]:
actual_stats = {}
import numpy as np
for op in compressed_model.get_ops():
    op_name = op.get_friendly_name()
    if op.get_type_name() == "Constant" and op.get_element_type() == ov.Type(np.uint8) and 'ZP' not in op_name:
        weight = op.data
        print(op_name, op.get_shape(), weight[:10], (weight.size - np.count_nonzero(weight)) / weight.size * 100)

Constant_571577_compressed [4096, 64, 64] [[[11  7  6 ... 11  6  9]
  [ 5  6 13 ...  8 12 11]
  [ 9 10 10 ...  8 11  5]
  ...
  [ 8  6  7 ... 14  8 10]
  [ 3  0 11 ...  8 11 10]
  [ 9  8  9 ...  5  8  7]]

 [[ 7  9  4 ... 13  4  5]
  [ 7 10  7 ...  9  4  9]
  [11 12  8 ... 11 12  7]
  ...
  [ 6  7  9 ...  5  7  5]
  [12  5  7 ...  0 13 10]
  [ 5  3 13 ...  7  9  9]]

 [[ 6  9  8 ...  9  9  9]
  [ 5  6 12 ...  7 10  0]
  [12  9  5 ...  9 12  9]
  ...
  [10 13  0 ...  6 10  9]
  [ 2  1  3 ... 14  8  8]
  [13 14  8 ...  6 11  9]]

 ...

 [[ 9  0  6 ...  9 12  9]
  [10 11  9 ... 10  4 11]
  [ 8  8 10 ...  6  6  9]
  ...
  [ 4  4 14 ...  7  4  5]
  [12 10 10 ... 12  6  9]
  [ 3 10  6 ...  8  8 10]]

 [[ 9  6  5 ... 10  6  4]
  [ 9  0  8 ... 14  3  6]
  [ 7  5  8 ... 15  6  8]
  ...
  [ 8 11 13 ...  5  3 12]
  [ 2 15  8 ...  5  1  5]
  [10  5  8 ... 13  6  6]]

 [[ 1 15 10 ...  5 10 13]
  [ 9 12  0 ...  5  3  2]
  [ 7  9 13 ... 14  9 12]
  ...
  [ 5  6 11 ...  3  6  6]
  [ 9 10  9 ...  3 10 

In [126]:
from datasets import load_dataset
# dataset = load_dataset("liwu/MNBVC", 'law_judgement', split='train', streaming=True)
# dataset = load_dataset("indiejoseph/wikitext-zh-yue", split='test', streaming=True)
dataset = load_dataset("clue", 'iflytek', split='test')
next(iter(dataset))
l=[(i, pair['sentence'][-1]) for i, pair in enumerate(dataset)]

In [123]:
sum([1 for ll in l if ll in ["。", "；", "~"]])
len(l)
# print(dataset)
# iter_data = iter(dataset)
# next(iter_data)
# next(iter_data)



2600

In [141]:
[(i,dataset[i]['sentence'][-10:]) for (i,ll) in l if ll in [".", "，", "6"]]

[(83, '戏内体验更多....'),
 (102, 'APP快速投保缴费，'),
 (143, '全新改版,为您而来.'),
 (247, ',Bugfixed.'),
 (248, '.增加侧滑返回功能.'),
 (289, '本升级到API\u300026'),
 (363, '..........'),
 (376, '..........'),
 (483, '私信内容丢失等问题.'),
 (584, '660206584，'),
 (603, '协助插件是一款软件，'),
 (721, '增加支持安卓4.4.'),
 (822, '增加声音，震动提醒.'),
 (894, '对手资源......'),
 (973, '可根据提示安装应用.'),
 (976, '物商城。产品特色1.'),
 (980, '4000320596'),
 (1106, '定性改进和错误修正.'),
 (1126, '提升应用稳定性...'),
 (1156, '等待新功能开发中..'),
 (1322, '化，修复部分bug.'),
 (1324, '网论坛参与互动』1.'),
 (1415, ';2.修改键盘样式.'),
 (1449, '的模拟经营游戏...'),
 (1622, '入破万。产品特色1.'),
 (1630, ',无限免费的....'),
 (1653, '们只帮您做4件事1.'),
 (1687, '司新人使用的客户端，'),
 (1709, '一切由你定夺....'),
 (1735, '与乐趣。游戏特色1.'),
 (1800, '容「3.0来了」1.'),
 (1910, '常容易的游戏，跳跃，'),
 (2136, 'e#DSudio1.'),
 (2178, '领先的英语培训机构，'),
 (2273, '全，马上开始吧...'),
 (2292, '侣。1，登录功能2，'),
 (2316, '音，触动你的心。1.'),
 (2416, '乐视盒子主要功能1.'),
 (2451, 'medevices.'),
 (2477, '==特色亮点==1.'),
 (2496, '计网校奖学金....'),
 (2526, '择按钮；功能优化1.')]

In [154]:
s = '1223.'
restricted_symbols = ('.', '3')
while s.endswith(restricted_symbols):
    print(s)
    s = s[:-1]
s

1223.
1223


'122'

In [155]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True)


In [93]:
name='Qwen/Qwen-7B-Chat'
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('/home/devuser/nlyalyus/projects/lm-evaluation-harness/cache/qwen-7b-chat/gptq', trust_remote_code=True, allowed_special='all')

In [105]:
tokenizer.special_tokens
tokenizer.unk_token_id
tokenizer.eos_token_id
tokenizer.eod_id

151643

In [113]:
s = '追书神器，小说追新更神器，汇集全网实时热门小说，5分钟内快速更新，上亿书友共享，拒绝书荒全网小说光速追更提醒，全站阅读无广告，多维推荐送好书，更有集吐槽书评交友等多位一体的高能社区，超好用的网文小说电子书追更神器更新内容V4.37新增新用户福利，新设备最多可15天免费读新增全新页面及功能调整，提高视觉与操作体验优化优化VIP专区的阅读体验修复修复上个版本已知问题'
l = tokenizer.batch_decode(tokenizer(s).input_ids)[-1]
len(l)

2

In [4]:
from optimum.intel.openvino import OVModelForCausalLM
from transformers import AutoTokenizer, AutoConfig
from optimum.intel.openvino import OVQwenModel
from optimum.utils import (
    NormalizedTextConfig, NormalizedConfigManager
)
NormalizedConfigManager._conf['qwen'] = NormalizedTextConfig.with_args(num_layers='num_hidden_layers', num_attention_heads='num_attention_heads', hidden_size='hidden_size')

pretrained = 'Qwen/Qwen-7B-Chat'
trust_remote_code = True
model_path = '/home/devuser/nlyalyus/projects/lm-evaluation-harness/cache/qwen-7b-chat/fp16'

config = AutoConfig.from_pretrained(pretrained, trust_remote_code=trust_remote_code)

tokenizer = AutoTokenizer.from_pretrained(
    pretrained,
    trust_remote_code=trust_remote_code,
    pad_token='<|extra_0|>',
    eos_token='<|endoftext|>',
    padding_side='left'
)

ov_model = OVQwenModel.from_pretrained(
    # NOTE: StableLM support
    # self.model = OVModelForCausalLM.from_pretrained(
    model_path,
    config=config,
    trust_remote_code=trust_remote_code,
    use_cache=True,
    # from_transformers=True
)
tokens = tokenizer("你好", return_tensors="pt")
print(tokens)

logits = ov_model(**tokens).logits

The argument `trust_remote_code` is to be used along with export=True. It will be ignored.
Compiling the model to CPU ...
Setting OpenVINO CACHE_DIR to /home/devuser/nlyalyus/projects/lm-evaluation-harness/cache/qwen-7b-chat/fp16/model_cache


{'input_ids': tensor([[108386]]), 'token_type_ids': tensor([[0]]), 'attention_mask': tensor([[1]])}


In [29]:
from datasets import load_dataset
dataset = load_dataset("indiejoseph/wikitext-zh-yue", split='test')
# next(iter(dataset))


Filter:   0%|          | 0/35231 [00:00<?, ? examples/s]

843

In [35]:
len(dataset.filter(lambda example: len(example["text"]) > 107))

644

In [27]:
sum(1 for example in dataset['text'] if len(example) > 150)
# l=[(i, pair['sentence'][-1]) for i, pair in enumerate(dataset)]

['松本城係日本一座古城，喺長野縣松本市。',
 '紐約兩大機場之一嘅拉瓜迪亞機場係以佢來命名嘅。',
 '被列為「邀請賽」嘅項目仍然會舉辦，但係唔會頒發獎牌，就算某啲比賽係正式項目，主辦城市仍然可以將嗰項列為邀請賽。',
 '牧羊狗能夠向狼做出一啲曖昧行為，例如係好幾隻牧羊狗一齊向住啲狼做出吠、邀請佢哋玩、或者有攻擊性嘅舉止等等嘅舉動，呢啲舉動可以幹擾狼，令到佢哋無所適從（不過噉做有陣時會搞到牧羊狗冇命）。',
 '東方風雲榜音樂盛典《十大金曲－年輪》',
 '2018年，李霖恩搖身一變成為導演兼經理人公司老闆，開戲之餘又簽下陳偉琪、杜大偉、湯沛宜、賴嘉瑩及Sugar Baby等藝人。',
 '八里區係中華民國新北市嘅一個區。',
 '佢係女王伊利沙伯二世嘅第二個曾孫，又係英國嘅第二順位繼承人。',
 '閔惠芬，中國二胡演奏家',
 '趙雷因為要準備個人演唱會，3月23號發表聲明，唔再參加突圍賽。',
 '早期消防車嘅設計佈局係，除咗司機同指揮官之外，其他消防隊員企或者坐喺消防車兩邊或後面，日曬雨淋。',
 '於是乎都美竹就唔夠膽走人，又繼續被人逼住飲酒，直到飲醉為止。',
 'Keyboard Warriors）係2018年上畫嘅港產片，由遊學修、林耀聲、鄧月平、陳凱琳、鄧麗欣主演，薛可正執導。',
 '遠古時曾認為思想在心，故此習慣上稱心算。',
 '譚駿賢係香港政治人，工黨黨員，前任屯門區議會友愛北選區議員。',
 '1962年屬民主大隊；',
 '儘管失去咗前桅同船首斜桅並起火，呢艘戰艦仲係非常快做好咗再次參戰嘅準備。',
 '第二長嘅河流係沙巴州嘅，全長。',
 '袁紹帶軍攻入宮中，殺曬啲宦官。',
 '《死屍死時四十四》 飾 阿俊',
 '香港迪士尼樂園設有三種不同類別嘅奇妙處處通可以全年入去玩，包括：',
 '《歡呼集》（詩集）1950，北京新華書店；',
 '1983年當選第六屆全國人民代表大會代表（任期從1983年6月至1988年3月）係湖北新聞出版界第一位全國人大代表。',
 '依家幾乎所有華裔泰國人都講泰文。',
 '多利喺2003年2月14號因病被人道毀滅。',
 '呢個指令集擴展嘅指令包含寄存器嘅局部位之間嘅運算，例如高位同低位之間嘅的加減運算；',
 '好多認知心理學家都有就「突然出現一個諗頭打前，個腦到底發生咗咩事」作出假說：',
 

In [39]:
from datasets import load_dataset
dataset = load_dataset("allenai/c4", 'zh', split='validation')

Resolving data files:   0%|          | 0/200 [00:00<?, ?it/s]

ValueError: Couldn't infer the same data file format for all splits. Got {'train': ('json', {}), 'validation': (None, {})}

In [51]:
from datasets import load_dataset
import re
dataset = load_dataset('shibing624/alpaca-zh')


In [70]:
# print(len(dataset['train']))
# dataset = dataset['train']
dataset = dataset.filter(
    lambda example: 100 < len(example['output']) < 400 and not re.search('[a-zA-Z]', example['output'])
)
print(len(dataset))


Filter:   0%|          | 0/15902 [00:00<?, ? examples/s]

15902


In [64]:
dataset

Dataset({
    features: ['instruction', 'input', 'output'],
    num_rows: 48818
})

In [44]:
bool(re.search('[a-zA-Z]', '根据给定的数据，我们可以使用梯形面积公式： 面积 = （下底 + 上底）  高 / 2。 带入数据得到： 面积 = (13厘米 + 16厘米)  12厘米 / 2 面积 = 174厘米² 因此，给定梯形的面积为174平方厘米'))

False